from sqlalchemy import Column, Integer, String, DateTime, Text, Float, Date, Boolean, DECIMAL
from sqlalchemy.sql import func

from app.database import Base


class WifiAdmin(Base):
    __tablename__ = "wifi_admin"

    dlb_a_id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    dlb_a_name = Column(String(255), nullable=False)
    dlb_a_phone = Column(String(15), nullable=False)
    dlb_a_ivr_number = Column(String(15), nullable=True)
    dlb_a_email = Column(String(255), nullable=False)
    dlb_a_password = Column(String(255), nullable=False)
    dlb_a_city = Column(String(100), nullable=False)
    dlb_a_state = Column(String(20), nullable=False)
    dlb_a_country = Column(String(100), nullable=False)
    dlb_a_address = Column(Text, nullable=False)
    dlb_a_zip_code = Column(String(15), nullable=False)
    dlb_a_image = Column(String(255), nullable=False)
    dlb_a_image_thumb = Column(String(250), nullable=False)
    dlb_a_status = Column(Integer, nullable=False, default=0, comment='0=active,1=inactive')
    dlb_admin_id = Column(Integer, nullable=False)
    dlb_a_created_date = Column(DateTime, nullable=False, server_default=func.now())
    dlb_a_type = Column(Integer, nullable=False, default=0, comment='0=user,1=teacher,3=super admin,6=employee')
    dlb_ds_id = Column(Text, nullable=False)
    dlb_a_subject = Column(String(255), nullable=True)
    dlb_a_promo = Column(String(255), nullable=True)
    dlb_profile_link = Column(String(255), nullable=True)
    dlb_tele_url = Column(String(255), nullable=True)
    dlb_pro_url = Column(String(255), nullable=True)
    dlb_pro_text = Column(String(255), nullable=True)
    dlb_super_admin = Column(Integer, nullable=False)
    dlb_code_name = Column(String(255), nullable=True)
    pending_lead = Column(Integer, default=0)
    user_lead = Column(Integer, default=0)
    dlb_pkg_id = Column(String(255), nullable=True)
    dlb_salary = Column(Float, nullable=True)
    dlb_branch_name = Column(String(255), nullable=True)
    dlb_center_name = Column(Text, nullable=True)
    dlb_cls_type = Column(Integer, nullable=False, default=0, comment='0=online,1=offline')
    dlb_aadhar_pdf = Column(String(255), nullable=True)
    dlb_other_pdf = Column(String(255), nullable=True)
    dlb_field = Column(String(255), nullable=True)
    dlb_ac_number = Column(String(255), nullable=True)
    dlb_ifsc_code = Column(String(255), nullable=True)
    dlb_emp_type = Column(String(255), nullable=True)
    dlb_counsellor_ids = Column(String(255), nullable=True)
    dlb_auto_lead = Column(Integer, nullable=False)
    dlb_emp = Column(Integer, nullable=False, default=0)
    dlb_joining_date = Column(Date, nullable=True)
    dlb_release_date = Column(Date, nullable=True)
    dlb_gender = Column(Integer, nullable=True, comment='0=male,1=female')
    dlb_dob_date = Column(Date, nullable=True)
    dlb_bank_name = Column(String(255), nullable=True)
    dlb_designation = Column(String(255), nullable=True)
    dlb_uan_number = Column(String(12), nullable=True)
    dlb_bank_holder_name = Column(String(255), nullable=True)
    dlb_esi_number = Column(String(20), nullable=True)
    dlb_pancard_number = Column(String(10), nullable=True)
    dlb_basic_salary = Column(DECIMAL(10, 2), nullable=True)
    dlb_hra = Column(DECIMAL(10, 2), nullable=True)
    dlb_transport_allowance = Column(DECIMAL(10, 2), nullable=True)
    dlb_other_allowance = Column(DECIMAL(10, 2), nullable=True)
    dlb_epf = Column(Integer, default=0, comment='0=no,1=yes')
    dlb_esi = Column(Integer, default=0, comment='0=no,1=yes')
    dlb_emp_code = Column(Integer, nullable=False)
    dlb_biometric_code = Column(String(255), nullable=True)